### ISSUE TITLE
你好，我想请问一下LINEMOD的合成数据集是自己下载还是去生成？

### ISSUE THREAD

**Issue by qingchenkanlu** [BoChenYS/ROPE#3]
https://github.com/BoChenYS/ROPE/blob/main/dataset/lm.py#L278

**Comment by BoChenYS** [comment]
是下载的，在BOP网站上下载。

**Comment by qingchenkanlu** [comment]
![微信截图_20220919112721](https://user-images.githubusercontent.com/44363924/190945269-4cb7bc95-68fb-497e-a0f0-a60093995894.png)
请问一下是具体哪一个呢？

**Comment by BoChenYS** [comment]
我记得是 Synt.training images of isolated objects 这个
